# clarifies that the right runtime for your Python code is Python 3.8. 
# This is enough for Google App Engine to do the necessary setup on its servers.
runtime: python37
service: default
instance_class: B1
basic_scaling:
  max_instances: 25
  idle_timeout: 5m

entrypoint: app.yaml

handlers:
- url: /
  script: login.app

- url: /login.html
  script: login.app

- url: /profile.html
  script: profile.app