
runtime: python37
service: default
instance_class: B1
basic_scaling:
  max_instances: 25
  idle_timeout: 5m

# handlers:
# - url: /
#   script: login

# - url: /login.html
#   script: login.app

# - url: /profile.html
#   script: profile.app